### GET all signatures
GET http://localhost:4000/api/signatures

###

### POST valid signature
POST http://localhost:4000/api/signatures
Content-Type: application/json

{
    "name": "Carol Davis",
    "email": "carol@wsu.edu",
    "city": "Pullman",
    "state": "WA",
    "signerType": "Student",
    "studentLevel": "Junior",
    "studentMajor": "Computer Science",
    "comment": "Early mornings are brutal in winter!"
}

###

### POST invalid signature (name under 5 chars)
POST http://localhost:4000/api/signatures
Content-Type: application/json

{
    "name": "Ada",
    "email": "ada@example.com",
    "city": "Spokane",
    "state": "WA",
    "signerType": "Student",
    "studentLevel": "Senior"
}
